ppi <- as.matrix(read.delim('./data/net_ppi.txt', header = FALSE, sep = "\t"))
exp <- as.matrix(read.delim('./temp/exp_net.txt', header = FALSE, sep = "\t"))
mirna <- as.matrix(read.delim('./data/net_mirna.txt', header = FALSE, sep = "\t"))
tf <- as.matrix(read.delim('./data/net_tf.txt', header = FALSE, sep = "\t"))
nodi_exp <- as.matrix(read.delim('./temp/exp.txt', header = FALSE, sep = "\t"))
nodi_ppi<-as.matrix(unique(rbind(as.matrix(ppi[,1]),as.matrix(ppi[,2]))))
nodi_mirna<-as.matrix(unique(rbind(as.matrix(mirna[,1]),as.matrix(mirna[,2]))))
nodi_tf<-as.matrix(unique(rbind(as.matrix(tf[,1]),as.matrix(tf[,2]))))
nodi<-as.matrix(unique(rbind(nodi_exp,nodi_ppi,nodi_mirna,nodi_tf)))
# exp
m<-match(exp[,1],nodi[,1])
w<-which(!is.na(m))
exp_temp<-as.matrix(exp[w,])
m<-match(exp_temp[,1],nodi[,1])
w<-which(!is.na(m))
exp_sel<-as.matrix(exp_temp[w,])
# ppi
m<-match(ppi[,1],nodi[,1])
w<-which(!is.na(m))
ppi_temp<-as.matrix(ppi[w,])
m<-match(ppi_temp[,1],nodi[,1])
w<-which(!is.na(m))
ppi_sel<-as.matrix(ppi_temp[w,])
# mirna
m<-match(mirna[,1],nodi[,1])
w<-which(!is.na(m))
mirna_temp<-as.matrix(mirna[w,])
m<-match(mirna_temp[,1],nodi[,1])
w<-which(!is.na(m))
mirna_sel<-as.matrix(mirna_temp[w,])
# tf
m<-match(tf[,1],nodi[,1])
w<-which(!is.na(m))
tf_temp<-as.matrix(tf[w,])
m<-match(tf_temp[,1],nodi[,1])
w<-which(!is.na(m))
tf_sel<-as.matrix(tf_temp[w,])
#
write.table(exp_sel,'temp/net_exp_unique_nodes.txt',sep='\t',col.names=FALSE,row.names=FALSE)
write.table(tf_sel,'temp/net_tf_unique_nodes.txt',sep='\t',col.names=FALSE,row.names=FALSE)
write.table(mirna_sel,'temp/net_mirna_unique_nodes.txt',sep='\t',col.names=FALSE,row.names=FALSE)
write.table(ppi_sel,'temp/net_ppi_unique_nodes.txt',sep='\t',col.names=FALSE,row.names=FALSE)
write.table(nodi,'temp/nodes.txt',sep='\t',col.names=FALSE,row.names=FALSE)

