void main() {
   module expressionFileFilter expFileFormat;
   module projectWindow projectPanel;
   module reverseEngineering gpro; 
   module cytoscapePanel csw;
   module genePanel gpan;
  projectPanel.loadDataSet("data/web100.exp", expFileFormat);
  datatype DSPanel p = gpan.getPanel("data/gpan.csv");
  datatype AdjacencyMatrix AM = gpro.getAdjacencyMatrix("data/web100.adj");
  print "hello";
  for (int i = 0; i < p.size(); i++) {
  print i;
  csw.computeAndDrawFirstNeighbors(p.get(i), AM);
  }
}
